 # This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-lambdas:
    strategy:
      matrix:
        func: ["activity", "authorizer", "onboard", "users"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cmd/${{matrix.func}}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      id: activity-build
      run: GOOS=linux GOARCH=amd64 go build -v -o bin/${{ matrix.func }}/bootstrap .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.func }}
        path: ./cmd/${{ matrix.func }}/bin
        retention-days: 5
        if-no-files-found: error

  terraform:

    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      TF_VAR_strava_secret: ${{ secrets.STRAVA_SECRET }}
  
    name: "Terraform plan"
    runs-on: ubuntu-latest
    needs: build-lambdas
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/download-artifact@v4
        with: 
          pattern: artifact-*
          path: ./artifacts
          merge-multiple: true
      - name: Show files
        run: ls -R

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

  