# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-activity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      id: activity-build
      run: GOOS=linux GOARCH=amd64 go build -v -o ./cmd/activity/bootstrap ./cmd/activity
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: activity-bootstrap
        path: ./cmd/activity/bootstrap
